spring:
  thymeleaf:
    cache: false
thrush:
  url:
    initUrl: https://kyfw.12306.cn/otn/login/init
    loginCaptcha: https://kyfw.12306.cn/passport/captcha/captcha-image?login_site=E&module=login&rand=sjrand
    refreshLoginCaptcha: https://kyfw.12306.cn/passport/captcha/captcha-image?login_site=E&module=login&rand=sjrand
    auth: https://kyfw.12306.cn/passport/web/auth/uamtk
    checkCode: https://kyfw.12306.cn/passport/captcha/captcha-check
    loginUrl: https://kyfw.12306.cn/passport/web/login
    uamtk: https://kyfw.12306.cn/passport/web/auth/uamtk
    authClient: https://kyfw.12306.cn/otn/uamauthclient
    stationName: https://kyfw.12306.cn/otn/resources/js/framework/station_name.js
    passenger: https://kyfw.12306.cn/otn/confirmPassenger/getPassengerDTOs
    ticketQuery: https://kyfw.12306.cn/otn/leftTicket/query
    checkUser: https://kyfw.12306.cn/otn/login/checkUser
    submitOrderRequest: https://kyfw.12306.cn/otn/leftTicket/submitOrderRequest
    initDc: https://kyfw.12306.cn/otn/confirmPassenger/initDc
    checkOrderInfo: https://kyfw.12306.cn/otn/confirmPassenger/checkOrderInfo
    getQueueCount: https://kyfw.12306.cn/otn/confirmPassenger/getQueueCount
    confirmSingleForQueue: https://kyfw.12306.cn/otn/confirmPassenger/confirmSingleForQueue
    queryOrderWaitTime: https://kyfw.12306.cn/otn/confirmPassenger/queryOrderWaitTime
    resultOrderForDcQueue: https://kyfw.12306.cn/otn/confirmPassenger/resultOrderForDcQueue
  user:
    username: username
    password: password
  image:
    imageLocation: /Users/xuyi/Downloads/12306
    url: http://192.168.23.142:8081
  ding:
    url: https://oapi.dingtalk.com/robot/send?access_token=
    token: 9048bea05b7f10ac4fb28445397554d8232611e03cf7c872b9cdc7526a1522fe
    notifyToken: cdfea81c7b8bfa12f8e89d94b47ab85f2b5d1a617980e6dd55a33ffc4ae20ae0
  host:
    domain: http://192.168.23.142:8080
  seat:
    type: swz:P,ydz:M,edz:O,rw:4,yw:3,yz:1,wz:1
